{
 "title": "Vaadin Frontend",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "User Interaction",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "User interaction",
     "type": "table",
     "gridPos": { "h": 19, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "limit": 20,
       "query": "{ .component =\"user-interaction\" && .target_xpath =~ \"\" && .event_type =~ \"\" }"
      }
     ]
    }
   ]
  },
  {
   "title": "DocumentLoad",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Document Load",
     "type": "table",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "limit": 20,
       "query": "{ .component = \"document-load\" && .http.url =~ \"\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Long tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Long Tasks (Frontend)",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "limit": 20,
       "query": "{ .component = \"long-task\"}"
      }
     ]
    }
   ]
  },
  {
   "title": "Page not found (HTTP 404)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Page not found",
     "type": "table",
     "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
     "targets": [
      { "limit": 20, "query": "{ .http.status_code = 404 } " }
     ]
    }
   ]
  }
 ]
}