receivers:
  otlp:
    protocols:
      http:
        cors:
          allowed_origins:
            - http://demo:8080
      grpc:

processors:
  batch:

exporters:
  prometheus:
    endpoint: collector:8090
  otlphttp:
    endpoint: http://tempo:4318
  loki:
    endpoint: http://loki:3100/loki/api/v1/push
    labels:
      resource:
        service.name: "service_name"
        host.name: "host_name"
      attributes:
        # Allowing 'severity' attribute and not providing a mapping, since the attribute name is a valid Loki label name.
        severity: ""
        http.status_code: "http_status_code"
      record:
        # Adds 'traceID' as a log label, seen as 'traceid' in Loki.
        traceID: "traceid"

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp]
    logs:
      receivers: [otlp]
      exporters: [loki]
